Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [25]:
import numpy as np
input_mat = np.array([1, 2, 3, 5])
def raisepower (values,increasing):
    if not increasing:
        op_matrix = np.array([x**(input_mat.size-i-1) for x in input_mat for i in range(input_mat.size)]).reshape(input_mat.size,input_mat.size)
        print(op_matrix)
    else:
        op_matrix = np.array([x**i for x in input_mat for i in range(input_mat.size)]).reshape(input_mat.size,input_mat.size)
        print(op_matrix)
raisepower(input_mat,False)

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


2.
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
Note: Solution submitted via github must contain all the detailed steps.
3.Output
This assignment consists of 200 marks and needs to be submitted in the upcoming session for
evaluation.

In [16]:
import numpy as np
from numpy import convolve

In [17]:
def movingaverage (values, window):
    weights = np.repeat(1.0, window)/window
    sma = np.convolve(values, weights, 'valid')
    return sma
x = [10,20,30,40,50,60,70,80,90,100]
y = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
xMA = movingaverage(x,4)
yMA = movingaverage(y,3)
print(xMA)
print(yMA)

[25. 35. 45. 55. 65. 75. 85.]
[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
